---

- name: "Update services file"
  blockinfile:
    dest: "{{ ansible_nagios_nrpe_services_file }}"
    block: |

      # Nagios services
      nrpe    {{ ansible_nagios_nrpe_port }}/tcp
  register: service_file_config
  notify:
    - Restart NRPE agent
    - Run NRPE check
    - Assert NRPE check was successful

- name: "Deploy NRPE configuration from template"
  template:
    src: "nrpe.cfg.j2"
    dest: "{{ ansible_nagios_nrpe_config_file }}"
  notify:
    - Restart NRPE agent
    - Run NRPE check
    - Assert NRPE check was successful

- name: "Ensure the NRPE daemon starts after reboot"
  service:
    name: "{{ ansible_nagios_nrpe_daemon_name }}"
    enabled: yes
