---

- include_vars: "RedHat.yml"
  when: ansible_os_family == 'RedHat'

- name: "Retrieve currently installed version"
  shell: "grep nagios_nrpe_version= {{ ansible_nagios_nrpe_nagios_path }}/nagios-nrpe.version | cut -d'=' -f2-"
  register: nagios_nrpe_version_installed
  changed_when: False
  ignore_errors: yes

- name: "Register trigger if NRPE agent installation should be berformed"
  set_fact:
    nrpe_agent_install: ansible_nagios_nrpe_reinstall_force or nagios_nrpe_version_installed.stdout != "{{ ansible_nagios_nrpe_version }}"

- include: install-nrpe.yml
  when: nrpe_agent_install

- include: configure-nrpe.yml
